# Read the Docs configuration file for Sphinx projects
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
      post_create_environment:
        # Install poetry
        - pip install poetry
        # Tell poetry to not use a virtual environment
        - poetry config virtualenvs.create false
      post_install:
        # Install dependencies
        - poetry install --with docs

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# python:
#   install:
#     - requirements: docs/requirements.txt