id: example
tasks:
- train
- test
env:
  name: presscontrol
  params:
    render_mode: "pressures"
algorithm:
  name: PPO
  params:
    learning_rate: 0.0003
  train_params:
    total_timesteps: 30000
    eval_freq: 5000
    n_eval_episodes: 1
wrappers:
- norm_obs
callbacks:
- EvalCallback
- TbMetricsCallback
- EpisodicDataCallback
paths:
  tensorboard_dir: "./tensorboard/"
  best_models_dir: "./best_models/"
  ep_metrics_dir: "./ep_metrics/"