id: ppo-press
tasks:
# - train
- test
env:
  name: presscontrol
  params:
    render_mode: "pressures"
algorithm:
  name: PPO
  params:
    learning_rate: 0.001
  train_params:
    total_timesteps: 10000
    eval_freq: 2000
    n_eval_episodes: 1
wrappers:
- norm_obs
callbacks:
- EvalCallback
- TbMetricsCallback
- EpisodicDataCallback
paths:
  tensorboard_dir: "./tensorboard/"
  best_models_dir: "./best_models/"
  ep_metrics_dir: "./ep_metrics/"