sample: clean
	./melgen-fusion-186_bdba ../data/sample.inp
	./melcor-fusion-186_bdba ../data/sample.inp
sgs: clean
	./melgen-fusion-186_bdba ../data/sgs2.inp
	./melcor-fusion-186_bdba ../data/sgs2.inp
clean:
	rm -f *.DIA
	rm -f *.MES
	rm -f *.OUT
	rm -f *.RST
	rm -f extDIAG
	rm -f MEGDIA
	rm -f MEGOUT
	rm -f MELDIA
	rm -f MELOUT
	rm -f *.dia
	rm -f *.out
	rm -f fort*
cleanall:
	rm -f *.DIA
	rm -f *.MES
	rm -f *.OUT
	rm -f *.RST
	rm -f *.DAT
	rm -f *.PTF
	rm -f extDIAG
	rm -f MEGDIA
	rm -f MEGOUT
	rm -f MELDIA
	rm -f MELOUT
	rm -f *.dia
	rm -f *.out
	rm -f fort*